# Generated by Django 5.0.4 on 2024-04-19 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_mobile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homonym',
            name='homonym_descriptions',
        ),
        migrations.RemoveField(
            model_name='homonym',
            name='homonym_meaning',
        ),
    ]
